alias ggrep="ggrep --color=auto"
alias dotnet="/usr/local/share/dotnet/./dotnet"
alias lock="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias sleeplock="pmset displaysleepnow"
alias protoc="/Users/Ricardo/Documents/Mestrado/PSD/protoc/bin/./protoc"
alias v="nvim"
alias py="python3"
alias c="clear"
alias o="open"
alias speedtest='curl -o /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias mysql='/usr/local/mysql/bin/mysql'
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias b="battery"
alias zshrc="v ~/.zshrc"
alias reload="source ~/.zshrc"
alias gpdot="sudo sh ~/.dotfiles.sh"
